#!/usr/bin/env node
/**
 * Nullius — VK Extractor
 *
 * Converts circuits/keys/verification_key.json (output of snarkjs setup)
 * into properly encoded Rust byte arrays for the Groth16 verifier contract.
 *
 * BN254 encoding rules:
 *   G1 points: 64 bytes  (x || y, each 32 bytes big-endian)
 *   G2 points: 128 bytes (x_c1 || x_c0 || y_c1 || y_c0, each 32 bytes big-endian)
 *   Scalars:   32 bytes  (big-endian)
 *
 * Note on G2 coordinate ordering:
 *   snarkjs outputs [c0, c1] but Stellar's BN254 host expects [c1, c0] (Montgomery form).
 *   This script handles the swap automatically.
 *
 * Usage:
 *   node scripts/extract_vk.js
 *
 * Output:
 *   Prints Rust code to paste into contracts/groth16_verifier/src/lib.rs
 *   Also writes contracts/groth16_verifier/src/vk_bytes.rs for cleaner integration
 */

const fs   = require("fs");
const path = require("path");

// ----------------------------------------------------------------
// Paths
// ----------------------------------------------------------------
const VK_PATH  = path.join(__dirname, "../circuits/keys/verification_key.json");
const OUT_PATH = path.join(__dirname, "../contracts/groth16_verifier/src/vk_bytes.rs");

if (!fs.existsSync(VK_PATH)) {
  console.error(`ERROR: ${VK_PATH} not found.`);
  console.error("Run circuits/scripts/setup.sh first to generate the verification key.");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(VK_PATH, "utf8"));

// ----------------------------------------------------------------
// Encoding helpers
// ----------------------------------------------------------------

/** Decimal string → 32-byte big-endian Uint8Array */
function decToBytes32(dec) {
  let val = BigInt(dec);
  const buf = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) {
    buf[i] = Number(val & 0xffn);
    val >>= 8n;
  }
  return buf;
}

/** G1 point [x, y, "1"] → 64-byte Uint8Array */
function encodeG1(point) {
  const x = decToBytes32(point[0]);
  const y = decToBytes32(point[1]);
  const out = new Uint8Array(64);
  out.set(x, 0);
  out.set(y, 32);
  return out;
}

/**
 * G2 point [[x_c0, x_c1], [y_c0, y_c1], ["1", "0"]] → 128-byte Uint8Array
 * Stellar BN254 expects: x_c1 || x_c0 || y_c1 || y_c0 (c1 before c0)
 */
function encodeG2(point) {
  const x_c0 = decToBytes32(point[0][0]);
  const x_c1 = decToBytes32(point[0][1]);
  const y_c0 = decToBytes32(point[1][0]);
  const y_c1 = decToBytes32(point[1][1]);
  const out = new Uint8Array(128);
  out.set(x_c1,  0);
  out.set(x_c0, 32);
  out.set(y_c1, 64);
  out.set(y_c0, 96);
  return out;
}

/** Uint8Array → Rust byte array literal */
function toRustBytes(arr) {
  const hex = Array.from(arr)
    .map((b) => `0x${b.toString(16).padStart(2, "0")}`)
    .join(", ");
  return `[\n        ${hex}\n    ]`;
}

/** Uint8Array → hex string for verification */
function toHex(arr) {
  return Array.from(arr).map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ----------------------------------------------------------------
// Encode all VK points
// ----------------------------------------------------------------
const alpha = encodeG1(vk.vk_alpha_1);
const beta  = encodeG2(vk.vk_beta_2);
const gamma = encodeG2(vk.vk_gamma_2);
const delta = encodeG2(vk.vk_delta_2);

if (!vk.IC || vk.IC.length < 4) {
  console.error(`ERROR: Expected 4 IC points (IC[0..3]), got ${vk.IC?.length}.`);
  console.error("Make sure you compiled with the correct number of public inputs (3).");
  process.exit(1);
}

const ic = vk.IC.map((point) => encodeG1(point));

// ----------------------------------------------------------------
// Generate vk_bytes.rs
// ----------------------------------------------------------------
const rustCode = `// AUTO-GENERATED by scripts/extract_vk.js — DO NOT EDIT MANUALLY
// Source: ${VK_PATH}
// Generated: ${new Date().toISOString()}
//
// BN254 verification key for the ReputationScore Groth16 circuit.
// Public inputs: [threshold, commitment, meets_threshold]

#![allow(dead_code)]

/// α (G1, 64 bytes): vk_alpha_1
pub const VK_ALPHA: [u8; 64] = ${toRustBytes(alpha)};

/// β (G2, 128 bytes): vk_beta_2
pub const VK_BETA: [u8; 128] = ${toRustBytes(beta)};

/// γ (G2, 128 bytes): vk_gamma_2
pub const VK_GAMMA: [u8; 128] = ${toRustBytes(gamma)};

/// δ (G2, 128 bytes): vk_delta_2
pub const VK_DELTA: [u8; 128] = ${toRustBytes(delta)};

/// IC[0] (G1, 64 bytes): constant term
pub const VK_IC_0: [u8; 64] = ${toRustBytes(ic[0])};

/// IC[1] (G1, 64 bytes): coefficient for public input[0] = threshold
pub const VK_IC_1: [u8; 64] = ${toRustBytes(ic[1])};

/// IC[2] (G1, 64 bytes): coefficient for public input[1] = commitment
pub const VK_IC_2: [u8; 64] = ${toRustBytes(ic[2])};

/// IC[3] (G1, 64 bytes): coefficient for public input[2] = meets_threshold
pub const VK_IC_3: [u8; 64] = ${toRustBytes(ic[3])};
`;

fs.writeFileSync(OUT_PATH, rustCode);

// ----------------------------------------------------------------
// Print summary + verification hex for cross-checking with snarkjs
// ----------------------------------------------------------------
console.log("✓ VK extraction complete");
console.log("");
console.log("Written to:", OUT_PATH);
console.log("");
console.log("Cross-check these hex values against your verification_key.json:");
console.log("  vk_alpha (first 16 bytes):", toHex(alpha).slice(0, 32), "...");
console.log("  vk_beta  (first 16 bytes):", toHex(beta).slice(0, 32),  "...");
console.log("  vk_gamma (first 16 bytes):", toHex(gamma).slice(0, 32), "...");
console.log("  vk_delta (first 16 bytes):", toHex(delta).slice(0, 32), "...");
console.log("  IC[0]    (first 16 bytes):", toHex(ic[0]).slice(0, 32), "...");
console.log("");
console.log("Next step:");
console.log("  Update contracts/groth16_verifier/src/lib.rs to import vk_bytes:");
console.log("  Add at top of file:  mod vk_bytes;");
console.log("  Then replace placeholder [0u8; N] arrays with vk_bytes::VK_ALPHA etc.");
console.log("");
console.log("Or run: node scripts/patch_verifier.js   (auto-patches lib.rs for you)");
