#!/usr/bin/env node
/**
 * Nullius — Verifier Auto-Patcher
 *
 * After extract_vk.js writes vk_bytes.rs, this script updates
 * contracts/groth16_verifier/src/lib.rs to import and use the real VK
 * instead of the placeholder zero-byte arrays.
 *
 * Compatible with soroban-sdk 27 API using Bn254G1Affine / Bn254G2Affine
 * and BytesN::from_array.
 *
 * Usage:
 *   node scripts/patch_verifier.js
 *
 * Safe to run multiple times — idempotent.
 */

const fs   = require("fs");
const path = require("path");

const LIB_PATH    = path.join(__dirname, "../contracts/groth16_verifier/src/lib.rs");
const VK_RS_PATH  = path.join(__dirname, "../contracts/groth16_verifier/src/vk_bytes.rs");

if (!fs.existsSync(VK_RS_PATH)) {
  console.error("ERROR: vk_bytes.rs not found. Run extract_vk.js first.");
  process.exit(1);
}

let src = fs.readFileSync(LIB_PATH, "utf8");

// Idempotency check
if (src.includes("mod vk_bytes;")) {
  console.log("lib.rs already patched — nothing to do.");
  process.exit(0);
}

// 1. Add mod declaration at top (after #![no_std])
src = src.replace(
  "#![no_std]",
  "#![no_std]\nmod vk_bytes;"
);

// 2. Replace placeholder VK point declarations with references to vk_bytes consts
//    Handles the soroban-sdk 27 API: Bn254G1Affine::from_bytes(BytesN::from_array(&env, &[0u8; N]))
const replacements = [
  // G1 points (64 bytes)
  [
    /let vk_alpha\s*=\s*Bn254G1Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*64\]\)\);/,
    "let vk_alpha = Bn254G1Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_ALPHA));",
  ],
  [
    /let vk_ic_0\s*=\s*Bn254G1Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*64\]\)\);/,
    "let vk_ic_0 = Bn254G1Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_IC_0));",
  ],
  [
    /let vk_ic_1\s*=\s*Bn254G1Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*64\]\)\);/,
    "let vk_ic_1 = Bn254G1Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_IC_1));",
  ],
  [
    /let vk_ic_2\s*=\s*Bn254G1Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*64\]\)\);/,
    "let vk_ic_2 = Bn254G1Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_IC_2));",
  ],
  [
    /let vk_ic_3\s*=\s*Bn254G1Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*64\]\)\);/,
    "let vk_ic_3 = Bn254G1Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_IC_3));",
  ],
  // G2 points (128 bytes)
  [
    /let vk_beta\s*=\s*Bn254G2Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*128\]\)\);/,
    "let vk_beta  = Bn254G2Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_BETA));",
  ],
  [
    /let vk_gamma\s*=\s*Bn254G2Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*128\]\)\);/,
    "let vk_gamma = Bn254G2Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_GAMMA));",
  ],
  [
    /let vk_delta\s*=\s*Bn254G2Affine::from_bytes\(BytesN::from_array\(&env,\s*&\[0u8;\s*128\]\)\);/,
    "let vk_delta = Bn254G2Affine::from_bytes(BytesN::from_array(&env, &vk_bytes::VK_DELTA));",
  ],
];

let patched = 0;
for (const [pattern, replacement] of replacements) {
  if (!pattern.test(src)) {
    console.warn(`WARN: pattern not found: ${pattern.toString().slice(0, 60)}... — skipping`);
    continue;
  }
  src = src.replace(pattern, replacement);
  patched++;
}

// 3. Update the TODO comment block
src = src.replace(
  /\/\/ ----------------------------------------------------------------\n\/\/ Verification key — TODO: replace with real values after setup\n\/\/ ----------------------------------------------------------------/,
  "// ----------------------------------------------------------------\n// Verification key — loaded from vk_bytes (generated by scripts/extract_vk.js)\n// ----------------------------------------------------------------"
);

fs.writeFileSync(LIB_PATH, src);

console.log(`✓ lib.rs patched successfully (${patched} replacements)`);
console.log("");
console.log("Next: rebuild the verifier contract");
console.log("  cargo build --target wasm32v1-none --release -p groth16-verifier");
