#!/usr/bin/env node
/**
 * ProofPay — Verifier Auto-Patcher
 *
 * After extract_vk.js writes vk_bytes.rs, this script updates
 * contracts/groth16_verifier/src/lib.rs to import and use the real VK
 * instead of the placeholder zero-byte arrays.
 *
 * Usage:
 *   node scripts/patch_verifier.js
 *
 * Safe to run multiple times — idempotent.
 */

const fs   = require("fs");
const path = require("path");

const LIB_PATH    = path.join(__dirname, "../contracts/groth16_verifier/src/lib.rs");
const VK_RS_PATH  = path.join(__dirname, "../contracts/groth16_verifier/src/vk_bytes.rs");

if (!fs.existsSync(VK_RS_PATH)) {
  console.error("ERROR: vk_bytes.rs not found. Run extract_vk.js first.");
  process.exit(1);
}

let src = fs.readFileSync(LIB_PATH, "utf8");

// Idempotency check
if (src.includes("mod vk_bytes;")) {
  console.log("lib.rs already patched — nothing to do.");
  process.exit(0);
}

// 1. Add mod declaration at top (after #![no_std])
src = src.replace(
  "#![no_std]",
  "#![no_std]\nmod vk_bytes;"
);

// 2. Replace placeholder VK point declarations with references to vk_bytes consts
const replacements = [
  // G1 points (64 bytes)
  [
    /let vk_alpha\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*64\]\);/,
    "let vk_alpha = Bytes::from_slice(&env, &vk_bytes::VK_ALPHA);",
  ],
  [
    /let vk_ic_0\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*64\]\);/,
    "let vk_ic_0 = Bytes::from_slice(&env, &vk_bytes::VK_IC_0);",
  ],
  [
    /let vk_ic_1\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*64\]\);/,
    "let vk_ic_1 = Bytes::from_slice(&env, &vk_bytes::VK_IC_1);",
  ],
  [
    /let vk_ic_2\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*64\]\);/,
    "let vk_ic_2 = Bytes::from_slice(&env, &vk_bytes::VK_IC_2);",
  ],
  [
    /let vk_ic_3\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*64\]\);/,
    "let vk_ic_3 = Bytes::from_slice(&env, &vk_bytes::VK_IC_3);",
  ],
  // G2 points (128 bytes)
  [
    /let vk_beta\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*128\]\);/,
    "let vk_beta  = Bytes::from_slice(&env, &vk_bytes::VK_BETA);",
  ],
  [
    /let vk_gamma\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*128\]\);/,
    "let vk_gamma = Bytes::from_slice(&env, &vk_bytes::VK_GAMMA);",
  ],
  [
    /let vk_delta\s*=\s*Bytes::from_slice\(&env,\s*&\[0u8;\s*128\]\);/,
    "let vk_delta = Bytes::from_slice(&env, &vk_bytes::VK_DELTA);",
  ],
];

for (const [pattern, replacement] of replacements) {
  if (!pattern.test(src)) {
    console.warn(`WARN: pattern not found: ${pattern} — skipping`);
    continue;
  }
  src = src.replace(pattern, replacement);
}

// 3. Remove the TODO comments block (they're now resolved)
src = src.replace(
  /\/\/ ----------------------------------------------------------------\n\/\/ Verification key — TODO: replace with real values after setup\n\/\/ ----------------------------------------------------------------\n/,
  "// Verification key — loaded from vk_bytes (generated by scripts/extract_vk.js)\n"
);

fs.writeFileSync(LIB_PATH, src);

console.log("✓ lib.rs patched successfully");
console.log("");
console.log("Next: rebuild the verifier contract");
console.log("  cargo build --target wasm32-unknown-unknown --release -p groth16-verifier");
